-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- change the leader key from "\" to ";" ("," is also popular)
-- vim.g.mapleader = ";"
-- use ;; for escape
-- http://vim.wikia.com/wiki/Avoid_the_escape_key
-- inoremap ;; <Esc>
-- vim.keymap.set(';;', '<Esc>')
-- vim.keymap.set({'n', 'i', 'c', 't'}, '<Leader>;', '<Esc>')